### ISSUE TITLE
An error occured! Status: COMPLETE Mermaid failed to parse data

### ISSUE THREAD

**Issue by jaypatrick** [R0tenur/visualization#103]
After installing extension for the first time attempting to view the schema, it immediately throws an error.

## Expected Behavior
Schema should be displayed

## Current Behavior
Throws an error immediately

An error occured!
Status: COMPLETE
Mermaid failed to parse data
Raw data:
"{\"hash\":{\"text\":\".\",\"token\":\"DOT\",\"line\":319,\"loc\":{\"first_line\":320,\"last_line\":320,\"first_column\":6,\"last_column\":19},\"expected\":[\"'NEWLINE'\",\"'EOF'\",\"'GENERICTYPE'\",\"'LABEL'\",\"'STYLE_SEPARATOR'\",\"'STRUCT_START'\",\"'ANNOTATION_END'\",\"'STR'\",\"'AGGREGATION'\",\"'EXTENSION'\",\"'COMPOSITION'\",\"'DEPENDENCY'\",\"'LINE'\",\"'DOTTED_LINE'\",\"'CALLBACK_NAME'\",\"'HREF'\",\"'UNICODE_TEXT'\",\"'NUM'\",\"'ALPHA'\"]}}"

Found a bug?
Report it here: https://github.com/R0tenur/visualization/issues

DISMISS

## Possible Solution
Display the schema

## Steps to Reproduce
Install extension, select datable, click on show schema (also, the word "occurred" is misspelled in the error message.

**Comment by docindata** [comment]
Having the same issue with identical error message in Azure Data Studio

**Comment by eulkloss** [comment]
Same issue...
![image](https://user-images.githubusercontent.com/4741244/227598713-655d4e7d-31eb-48f3-8b10-8317a01241e0.png)

**Comment by CAPREITMiruss** [comment]
Same here.

**Comment by primaproxima** [comment]
Same here.

**Comment by R0tenur** [comment]
I have not been able to reproduce this, but might be because I just use sample db's
Would appreciate if someone could provide the generated md 

- dissmiss alert
- export the md

**Comment by bmschwa** [comment]
Hey @R0tenur, I'm getting the same error.   when I dismiss the alert, I don't see a way to export the mark down.... happy to send the offending piece if you can either point me towards instructions of how to export.

**Comment by R0tenur** [comment]
<img width="759" alt="Screenshot 2023-09-05 at 12 13 39" src="https://github.com/R0tenur/visualization/assets/12293736/57ccd428-ef6a-4695-89ce-6aa0d83e2f93">

On top where,  it says "Export"
Select "md"

**Comment by bmschwa** [comment]
... Got it, when I updated to 0.9.1 - problem went away (and I see an export button).

Thanks much for the quick response.

**Comment by R0tenur** [comment]
I have done som adjustments to prevent syntax errors, but since I am not able to reproduce it on any of my dbs its very hard to test it

**Comment by R0tenur** [comment]
Will close this since no new activity since the latest release and I am not able to reproduce
