### ISSUE TITLE
Export to SVG format not working

### ISSUE THREAD

**Issue by aparady** [R0tenur/visualization#118]
Hello, 
congratulations for this great schema visualization tool!
unfortunately, when I click on the EXPORT and select SVG, I click save and the popup closes normally but no file is saved to the folder.. 
the .MD file saves normally however so I'm not sure what I'm doing wrong ?!
thanks in advance,
André P

**Comment by sergiuser1** [comment]
Are you sure you are on the latest version (v0.8.5)? I had the same issue since the version found through the extension menu was older and I encountered the same bug.

**Comment by aparady** [comment]
Awww thank you for your feedback, ADS directed me to v0.8.2 and downloading v0.8.5 fixed the problem right away.
Many thanks once again
:)
