### ISSUE TITLE
Cannot Visualize My Azure Database

### ISSUE THREAD

**Issue by ddieppa** [R0tenur/visualization#12]
## Expected Behavior

Click on the Schema Visualization icon and see the db diagram

## Current Behavior

Click on the Schema Visualization icon and got this error:

```log
Errors:
Error getting data: Failed to connect to connectionstringtoazuredb - getaddrinfo ENOTFOUND  connectionstringtoazuredb 
Could not build chart from the recived data
{"databaseRaw":[],"errors":["Could not build chart from the recived data"],"status":"ERROR"}
```

## Context (Environment)

Azure Data Studio
Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

## Detailed Description

![image](https://user-images.githubusercontent.com/10607192/87830228-9e79ad00-c84e-11ea-9cb4-bb504d6320ca.png)

**Comment by R0tenur** [comment]
Is the db running on port 1433? If not, there are a recently added release that is not yet linked from the store.

https://github.com/R0tenur/visualization/releases/tag/v0.4.0

**Comment by ddieppa** [comment]
@R0tenur yes it is running on port **1433**
this is the format of the connection string:
`tcp:ourserver.database.windows.net,1433`

**Comment by R0tenur** [comment]
Can you check if the latest fix is working?
https://github.com/R0tenur/visualization/releases/tag/v0.5.0
I have not been able to reproduce the error

**Comment by ddieppa** [comment]
I did install the latest fix, and not getting the error but the schema never appears
![image](https://user-images.githubusercontent.com/10607192/88436491-659f8200-cdd2-11ea-9ab5-44296de67048.png)
stay in loading forever

**Comment by R0tenur** [comment]
Can you show how you ar filling in the credentials view? Ofc not the real credentials but the structure in the input fields.

**Comment by ddieppa** [comment]
here is a picture of the connection details, ofc not the real ones
![image](https://user-images.githubusercontent.com/10607192/88557706-8f39f280-cff8-11ea-9dee-0393c22357a3.png)
