### ISSUE TITLE
FK & PL letters not showing in diagram via extension within Azure Data Studio for Mac.OS

### ISSUE THREAD

**Issue by TheLegitMaggiNoodles** [R0tenur/visualization#123]
Hi,
Am on a mac.os and had to install docker, to utilise azure data studio for a class activity.
As part of creating dbs, I want to be able to see data visualisation - diagram similar to function via SQL server.

As a workaround solution - I d/l schema visusalization and can see the diagram, but I don't see symbols Primary Key (PK) or Foreign Key (FK) in diagram (similar to SQL output).

## Expected Behavior

Should show PK or FK in diagram to help easily identify relationships too.

## Current Behavior

Just shows diagram, but no letters within the name as a quick way to tell if it's a PK or FK.

## Steps to Reproduce

[1.](url) 
2. 
3.
4.
/
## Context (Environment)
 
I am spending a lot more time staring at the diagram trying to workout if it's PK, FK or normal. Would like to easily reflect relationships in DB and see it also with the diagram created.

Show PK or FK - as in state the letters in the diagram.

**Comment by R0tenur** [comment]
Available in the most recent version: https://github.com/R0tenur/visualization/releases

**Comment by TheLegitMaggiNoodles** [comment]
Wow - Thank you so much for the update and adding in the first column -
wasn't expecting that, but it's great for quick snapshot.

[image: Library DB.png]
