### ISSUE TITLE
Wrong relation direction

### ISSUE THREAD

**Issue by maxfaa** [R0tenur/visualization#138]
The result provided by the extension isn't correct. It doesn't match my teacher's schema.
## Expected Behavior

<img width="861" alt="image" src="https://github.com/R0tenur/visualization/assets/71935156/3678fbce-5b63-4d6d-92b2-85ec0b0fc59a">

## Current Behavior

<img width="822" alt="image" src="https://github.com/R0tenur/visualization/assets/71935156/c81ca28f-7629-4ca0-83c1-cab6a99d9a98">

## Steps to Reproduce

1. Use the scripts in the zip below
[scripts-supplied-by-my-teacher.zip](https://github.com/R0tenur/visualization/files/13704929/scripts-supplied-by-my-teacher.zip)
2. Run these
3. Open the database schema visualization 

## Context

First, thank you so much. I'm a computer science student and in one of my courses I have to use SSMS. Unfortunately I'm a MacOS user (and one of my friends use Ubuntu). Since SSMS isn't available of ours OSs, we use Azure Data Studio. So thanks a lot for creating this extension that counters the lack of schema virtualisation feature.

However, we have a big issue: the schemas provided by your extension are kinda reversed. Like, if we look (screenshots above) at the relation between the "commande" and "employe" tables, we can see this:
<img width="249" alt="Screenshot 2023-12-18 at 15 57 20" src="https://github.com/R0tenur/visualization/assets/71935156/5b85df46-842b-43b0-a51a-5f1fced1939e">
while it should look like this:
<img width="250" alt="Screenshot 2023-12-18 at 15 55 03" src="https://github.com/R0tenur/visualization/assets/71935156/227f319d-7d60-4c3d-8b9e-18936c38781f">

**Comment by jmanghani** [comment]
Yup, have the same problem here.

**Comment by psoszynski** [comment]
Still an issue. Have the same problem. Please fix.

**Comment by R0tenur** [comment]
I am currently not activly working on this project. Feel free to open a PR 

Issue is probably here: https://github.com/R0tenur/visualization/blob/master/backend%2Fsrc%2Fservices%2Fbuilder.service.ts#L49

And should be clear how to run in locally in the readme.

**Comment by tslever** [comment]
I may have addressed this issue with pull request 153: Corrected Generation Of Entity Relationship Diagram (https://github.com/R0tenur/visualization/pull/153). Would you please review?

**Comment by R0tenur** [comment]
Thanks to @tslever this is resolved in https://github.com/R0tenur/visualization/releases/tag/v0.9.4
