### ISSUE TITLE
Can't install extension to Azure Data Studio

### ISSUE THREAD

**Issue by sitary** [R0tenur/visualization#14]
VSIX Installer says install failed because "One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code."

[dd_VSIXInstaller_20200721150805_2708.log](https://github.com/R0tenur/visualization/files/4956077/dd_VSIXInstaller_20200721150805_2708.log)

**Comment by Ci5co** [comment]
Hi! I could do it but not though double clicking the downloaded file, using the provided menu item instead. And it works as intended: 
![image](https://user-images.githubusercontent.com/23027643/88377222-1855ed00-cd9f-11ea-87dc-aa6b82f48262.png)

**Comment by sitary** [comment]
Thank you! That worked perfectly.

**Comment by AlexKeySmith** [comment]
Out of interest is it possible to install directly from the gallery rather than downloading? Or if not it would be great to document this step in the details of the gallery page.

Great work btw!

**Comment by R0tenur** [comment]
I did try to publish an direct download link aswell as an link to the latest release instead if specific version number. Apparently this is not allowed for none microsoft packages.
