### ISSUE TITLE
Incorrectly adding default port to connection

### ISSUE THREAD

**Issue by cg3y** [R0tenur/visualization#15]
## Expected Behavior

The connection to the server should use the connection name/instance/port from the Azure Data Studio configured connection

## Current Behavior

Instead, port 1433 is being added to the connection, causing an inability to use the tool if the connection is on a non-standard port. For example, if my server connection is "myserver.domain.com,1400" then the software is attempting to connect to "myserver.domain.com,1400,1433" which clearly won't work. As such I can't use this at all for our servers that run on non-standard ports.

## Steps to Reproduce

1. Connect to a SQL Server instance running on a port other than 1433 in Azure Data Studio
2. "Manage" the server
3. Click "Schema Visualization" on the management screen.
4. You'll be unable to connect and see the problem.

**Comment by cg3y** [comment]
User error. Not an issue.

**Comment by R0tenur** [comment]
This is actually a bug within the version that are linked from the extention store. If you use the latest version https://github.com/R0tenur/visualization/releases/tag/v0.4.0 it should be fixed
