### ISSUE TITLE
Connection string with non-default port are failing

### ISSUE THREAD

**Issue by cviorel** [R0tenur/visualization#24]
When defining a connection string with a non-default tcp port, the connection fails.
e.g. `192.168.1.250,10002`
## Expected Behavior

the connection to the database should be done on port 10002 instead of the default 1433

## Current Behavior

<img width="695" alt="Screenshot 2020-11-04 121055" src="https://user-images.githubusercontent.com/125662/98105175-dd804c80-1e97-11eb-951d-ca1f3f7b1863.png">

## Steps to Reproduce

connect to a sqlinstance on a non-standard tcp port
e.g. 
`192.168.1.250,10002` 
`<fqdn>,<tcp_port> `

**Comment by R0tenur** [comment]
Duplicate of #10 and #15
You are probably using an old version, please have a look under the tab releases in this repo.

**Comment by cviorel** [comment]
Indeed, my version was not the latest one.
After upgrading, I can confirm it's working as expected.
