### ISSUE TITLE
Error "Can not build chart..."

### ISSUE THREAD

**Issue by Atlas-app** [R0tenur/visualization#26]
I get this error when I try to load the extension in different sql databases. 

> Errors:
> Error getting data: Failed to connect to .:1433 - getaddrinfo EAI_AGAIN .
> Could not build chart from the recived data
> {"status":"ERROR","errors":["Could not build chart from the recived data"],"databaseRaw":[]}
>

**Comment by R0tenur** [comment]
Hello, are youuing the latest version of the extention? Checkout "releases" in this repo
