### ISSUE TITLE
[Feature request] Cardinality

### ISSUE THREAD

**Issue by VincentTam** [R0tenur/visualization#28]
Thanks for great extension.  It's very easy to use.  Can you consider adding the functionality for cardinality?

![Screenshot for plugin](https://user-images.githubusercontent.com/5748535/100669726-1eb43100-335e-11eb-9114-802ea9ad0f14.png)

**Comment by R0tenur** [comment]
Available in the most recent version: https://github.com/R0tenur/visualization/releases
