### ISSUE TITLE
Error connecting to database not at port 1433

### ISSUE THREAD

**Issue by vaughajm** [R0tenur/visualization#30]
Fails to connect to database on instance not at port 1433. 
Output:

Errors:
Error getting data: Failed to connect to localhost,1401:1433 - getaddrinfo ENOTFOUND localhost,1401
Could not build chart from the recived data
{"status":"ERROR","errors":["Could not build chart from the recived data"],"databaseRaw":[]}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by R0tenur** [comment]
Are you running the most recent version of the extention? It can be downloaded on the release tab in this repo.

**Comment by vaughajm** [comment]
Sorry, I'd downloaded the version from ADS. The current version works fine.

Thank You
Joe
