### ISSUE TITLE
Zoom Would be Helpful

### ISSUE THREAD

**Issue by JediSQL** [R0tenur/visualization#32]
## Expected Behavior
With a database with many tables, the diagram is very spread out. It would be helpful if one could zoom out to find the table being looked for, and then zoom back in to see the details.

## Current Behavior
No zoom. Hard to find stuff in a database with a high table count.

**Comment by R0tenur** [comment]
This should be resolved in [v0.7.0](https://github.com/R0tenur/visualization/releases/tag/v0.7.0)
