### ISSUE TITLE
Table Gets Column Names in Triplicate

### ISSUE THREAD

**Issue by JediSQL** [R0tenur/visualization#33]
## Expected Behavior
The columns of a table should be listed only once in the rectangle for the table.

## Current Behavior
One of my tables had the columns listed three times (see screenshot).

## Steps to Reproduce
I just double tapped my complex database, tapped on "Schema Visualization," and waited a few seconds.

## Context (Environment)
SQL Server 2017 database. Originally SQL 2000, then upgraded to SQL 2008, then 2014, and then 2017.
![Schema Visualization XML_MN 1](https://user-images.githubusercontent.com/8801305/103238470-aeb6ad80-48ff-11eb-8f0b-2d15b944148c.png)

**Comment by JediSQL** [comment]
None the less, good start. Thank you. It looks like it could be fun by the time it makes it to 1.x. :-)

**Comment by R0tenur** [comment]
Wow! Fun bug! Should be an easy fix :)

**Comment by JediSQL** [comment]
Oh. I just thought of something. The same identical table exists in three different schemas.

**Comment by R0tenur** [comment]
This should be resolved in [v0.7.0](https://github.com/R0tenur/visualization/releases/tag/v0.7.0)
