### ISSUE TITLE
Install link goes to outdated version

### ISSUE THREAD

**Issue by todofixthis** [R0tenur/visualization#37]
Issue Type: <b>Bug</b>

# Repro
1. Open Extensions panel.
2. Find Schema Visualisation extension.
3. Click on Install button.

Expected behaviour:
Latest version of the extension is installed.

Actual behaviour:
Opens Github releases page for v0.3.0 of the extension (latest version as of this writing is v0.6.0).

Extension version: 0.6.0
Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:18:54.187Z)
OS version: Darwin x64 20.3.0

**Comment by R0tenur** [comment]
Fixed for now, I need to open a PR to the datastudio repo for each version. I shall automate it from a github action when I get the time
