### ISSUE TITLE
Installation failed as VS Code is not installed

### ISSUE THREAD

**Issue by RuneAndersen** [R0tenur/visualization#38]
When trying to install the VSIX it fails as it cannot locate Visual Studio Code. Visual Code is not installed at the current system but the installer expect it to and thereby fails.

## Expected Behavior
Should be able to install without VS Code installed

## Current Behavior
Fails during installation

## Possible Solution
Do not require VS Code
Is VS / VS Code dependency really required as it is an extension for Azure Data Studio?

## Steps to Reproduce
Have a machine with full VS but without VS Code
Run installer

## Detailed Description
Log from installer
[dd_VSIXInstaller_20210412102444_3834.log](https://github.com/R0tenur/visualization/files/6295065/dd_VSIXInstaller_20210412102444_3834.log)

![image](https://user-images.githubusercontent.com/15083790/114365035-5176fd00-9b7a-11eb-8a64-a02e0c29e3e0.png)

**Comment by R0tenur** [comment]
You are not installing by double clicking the vsix. In the extention gallery, press the three dots on top and select "Install from vsix"
<img width="621" alt="image" src="https://user-images.githubusercontent.com/12293736/114386488-9195aa00-9b91-11eb-9f63-0e70894fd4b9.png">

**Comment by RuneAndersen** [comment]
Your guide of clicking the three dots worked :+1:

I was clicking the install button and then downloading the vsix as guided by Azure Data Studio.
![image](https://user-images.githubusercontent.com/15083790/114388951-a889cb80-9b94-11eb-995c-c60bd6e5641a.png)

I suggest you might include this installation information at the splash screen displayed with product info.
