### ISSUE TITLE
Request: show schema name (maybe optional)

### ISSUE THREAD

**Issue by aisbergde** [R0tenur/visualization#39]
## Expected Behavior

It should be possible to show also the schema.

## Current Behavior

only the table names are shown.

## Possible Solution

- show schemas by default
- add an option to show or hide schema name

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

SQL Server, any database containig tables in schemas

**Comment by R0tenur** [comment]
Thank you for reporting!
This should be added in [v0.8.5](https://github.com/R0tenur/visualization/releases/tag/v0.8.5)
