### ISSUE TITLE
New frontend

### ISSUE THREAD

**Issue by R0tenur** [R0tenur/visualization#6]
Mermaid is not dynamic enough and will not work that well when more advanced features are developed.

**Comment by AlexKeySmith** [comment]
That's interesting you are hitting the limitations of mermaidjs. Mermaid does have the great advantage of being something easily copied into the likes of Azure DevOps wiki's etc etc.

I wonder if there are limitations to propose improvements to mermaidjs itself?

Out of interest what sort of things you are thinking of?

Great work btw!

**Comment by AlexKeySmith** [comment]
Oooo actually Azure DevOps doesn't support classDiagrams, but I wish it did!

**Comment by R0tenur** [comment]
Hi!
I am glad that you like my project.
Totally agree that mermaid is a great tool. It actually made it possible for me to build the main part of this extention in a few hours.

Some of the features I miss is:
- Allowing the user to dragging tables around on the screen. Now it's kind of static.
- Be able to build more complex visualization, examples would be looking into what procedures are modifing the contents of an table.
- make the UI look more like the data studio in general.
- More structured code on the UI (this could ofc be done using mermaid)
- With an none markup-structure of the object it would be possible to build a graphical database builder, where you could design your db from the UI and then create it with a press of a button.

I know that some of the git provides mermaid support within their markdown files. Could always keep the possibility to export as mermaid markdown.

**Comment by R0tenur** [comment]
This should be resolved in [v0.7.0](https://github.com/R0tenur/visualization/releases/tag/v0.7.0)
