### ISSUE TITLE
Zoom not working properly?

### ISSUE THREAD

**Issue by raoulteeuwenPE** [R0tenur/visualization#61]
## Expected Behavior
Some natural way of zooming to a certain part, and unzooming. Also maybe improve how the zoomed-in image pans compared to ones mouse movement

## Current Behavior
When i zoom, i don't have an idea how to control where it is zooming. Also, with the db's i work with, when zoomed in and trying to scroll to the part that is invisible, the area i can scroll in 'cuts off' while only showing a part of the total visualization, making it impossible to reach the non-shown part. Also, when using the mouse the screen behaves unexpected, like it is trailing in my mouse movement or planning curved paths through the zoomed in image.

## Possible Solution
Not sure whether i don't know how to use it. Would love it if one can, while zoomed out, position the mouse cursor at some point in the visualization, and than scroll-wheel zooming in at the part your cursor is at

## Steps to Reproduce
1. Open db with for instance 126 tables
2. Start visualizing it
3. Try to zoom in at a section
4. Find out navigating in the zoomed-in image is unintuitive (strange curved paths of how the zoom behaves/pans), you don't have control of where you're going to zoom in, and zoomed-in-image, when panning to edges, is cut off from (unable to reach all parts of) total zoomed out image.

## Context (Environment)
ADS

## Detailed Description
I hope the above describes my experience and expectation enough

## Possible Implementation
? But please enjoy your parental leave first ;-)

**Comment by DanielHabenicht** [comment]
I can reproduce this: 
1. Big Schema 
2. Zoom in
3. Scroll (via mouse clicks) to the right. 
4. Right side is cut off (and you can't scroll further)
