### ISSUE TITLE
No longer creates/shows a schema

### ISSUE THREAD

**Issue by ssnyder** [R0tenur/visualization#69]
Installed new plugin, reloaded window....tried to see the schema visualization and it just waits and waits and waits....never coming back!

## Expected Behavior
I should see the schema!

Version: 1.32.0 (user setup)
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:08:28.086Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

just downloaded and installed the 0.7.1 release of this extension

**Comment by R0tenur** [comment]
Yeah, to update the version I need to submit a pullrequest to the azure data studio repo. I have decided to automate that process before I do it again, but have not had the time
