### ISSUE TITLE
The Schema Visulatisation is returning blank when selecting DB

### ISSUE THREAD

**Issue by seppu** [R0tenur/visualization#7]
I installed this extension with much hope. But I am not able to see any visualisation.its returning blank on clicking on the Visulatisation tab. Please see the screen shot below
![image](https://user-images.githubusercontent.com/7526379/77276416-b9a83600-6d0e-11ea-8725-3e605d623f72.png)

**Comment by R0tenur** [comment]
Are your db located on a server or on localhost?
What kind of authentication are used?

**Comment by seppu** [comment]
The DB is located on a server. Uses windows authentication as it's connected to the corporate AD

**Comment by MikaTas** [comment]
Yes.. the schema visualizer is blank. No loading indicator, no nothing. Using Azure SQL Server and administrative access account.

**Comment by R0tenur** [comment]
I'm getting the schema by querying sys.objects and information_schema.
Cold you please try the following query:   https://github.com/R0tenur/visualization/blob/4be706d15b112b22eaee4b09d8a10790a6a770f0/src/repositories/mssql.repository.ts#L43 and attach the error in this issue?

**Comment by fede1608** [comment]
Msg 208, Level 16, State 1, Line 1
Invalid object name 'SYS.FOREIGN_KEY_COLUMNS'.

**Comment by holajoyce** [comment]
This is currently only available in sql server and not on postgres yet, right?   Really looking forward to using this as well.  But am only on PG.

**Comment by R0tenur** [comment]
> Msg 208, Level 16, State 1, Line 1
> Invalid object name 'SYS.FOREIGN_KEY_COLUMNS'.

Thank you! I have created a new query for getting the tables that is not dependent on the SYS objects.
I would appriciate if you could try the follwing query:
https://github.com/R0tenur/visualization/blob/a4421ea1b1b179035c302d2c88d3dfca183511b7/src/repositories/mssql.repository.ts#L165

**Comment by fede1608** [comment]
> > Msg 208, Level 16, State 1, Line 1
> > Invalid object name 'SYS.FOREIGN_KEY_COLUMNS'.
> 
> Thank you! I have created a new query for getting the tables that is not dependent on the SYS objects.
> I would appriciate if you could try the follwing query:
> https://github.com/R0tenur/visualization/blob/a4421ea1b1b179035c302d2c88d3dfca183511b7/src/repositories/mssql.repository.ts#L165

That actually worked!

**Comment by R0tenur** [comment]
> > > Msg 208, Level 16, State 1, Line 1
> > > Invalid object name 'SYS.FOREIGN_KEY_COLUMNS'.
> > 
> > 
> > Thank you! I have created a new query for getting the tables that is not dependent on the SYS objects.
> > I would appriciate if you could try the follwing query:
> > https://github.com/R0tenur/visualization/blob/a4421ea1b1b179035c302d2c88d3dfca183511b7/src/repositories/mssql.repository.ts#L165
> 
> That actually worked!

Great, that fix is included in the latest version: https://github.com/R0tenur/visualization/releases/tag/v0.3.0

**Comment by R0tenur** [comment]
With the latest version errors are displayed in the UI
