### ISSUE TITLE
Stuck on getting the database structure, no error

### ISSUE THREAD

**Issue by mcrobbj-abrdn** [R0tenur/visualization#72]
## Expected Behavior

Double tap your db and press "Schema Visualization" on the dashboard.
It should produce a visualisation of the schema, but it just sits on Getting the database structure... no error

## Current Behavior

Spins around and never produces anything, not even an error

## Steps to Reproduce

1. Double tap your db and press "Schema Visualization" on the dashboard.
2. Getting the database structure...
3.
4.

## Context (Environment)

Azure

**Comment by R0tenur** [comment]
Are you using the moster recent version of the extention? Look under "realeases"

**Comment by drk-mtr** [comment]
Thanks for sharing this plugin! I have the same issue, using v0.8.2 of the plugin and v1.34.0 of Azure Data Studio.

It shows `Getting the database structure...` and nothing happens.

In the developer tools console I see this - apologies for the poor formatting:

```
[Extension Host] 
rejected promise not handled within 1 second: Error: Query has no results to return

[Extension Host] stack trace: Error: Query has no results to return	
    at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:67721	
    at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68015	
    at Immediate.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68374)	
    at processImmediate (internal/timers.js:461:21)

[[object Object]]Query has no results to return

Error: Query has no results to return
    at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:67721
    at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68015
    at Immediate.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:1:68374)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by mcrobbj-abrdn** [comment]
Seems to work with 0.8.2 ( which you have to manually load) I now have an issue with exporting, seem to be able to do MD but not svg. Just goes to a file prompt with sas as and filetype is fileformat ( svg was highlighted in ADS)

**Comment by drk-mtr** [comment]
@mcrobbj-abrdn be kind to the developer and raise as a new issue if you believe it's a new issue, they've been kind enough to share free software so posting unrelated issues on a closed thread won't be helpful for them ;)
