### ISSUE TITLE
Export as svg of an created diagram fails

### ISSUE THREAD

**Issue by tobKai1** [R0tenur/visualization#88]
When exporting a created diagram as a svg-File the following 
error 'The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined'
shows up in the 'Runtime Status' tab of the 'Schema Visualization' Extension.

**Comment by JoeZhongTR** [comment]
Is there an older version that this feature works?

**Comment by R0tenur** [comment]
> Is there an older version that this feature works?

Yes, v0.8.3
Also I am on it.

**Comment by R0tenur** [comment]
Thank you for reporting!
This should be resolved in [v0.8.5](https://github.com/R0tenur/visualization/releases/tag/v0.8.5)
