### ISSUE TITLE
FR : Visualize Views

### ISSUE THREAD

**Issue by Rom1deTroyes** [R0tenur/visualization#99]
# Feature Request : Visualize Views

I'm working on a Datawarehouse where users select lines only from Views.
The Tables have no relations, and each View takes information from multiple Tables with proper Join ... On ... statements.

## Expected Behavior

Be able to visualise the relation between the Views and the Tables.

## Current Behavior

It seems that Views are not visible, and my tables are just lined up side by side (well, has they should be...).

**Comment by R0tenur** [comment]
Thanks for reporting!
You are correct, views är not included as of today.

**Comment by R0tenur** [comment]
Available in the most recent version: https://github.com/R0tenur/visualization/releases
